"""Update Enum in groups to be not nullable.

Revision ID: be9814083a88
Revises: 5ccd9c609ee1
Create Date: 2024-06-26 22:52:41.920756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be9814083a88'
down_revision = '5ccd9c609ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=postgresql.ENUM('avatar1', 'avatar2', 'avatar3', 'avatar4', 'avatar5', 'avatar6', 'avatar7', 'avatar8', 'avatar9', 'avatar10', name='avatar_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=postgresql.ENUM('avatar1', 'avatar2', 'avatar3', 'avatar4', 'avatar5', 'avatar6', 'avatar7', 'avatar8', 'avatar9', 'avatar10', name='avatar_enum'),
               nullable=True)

    # ### end Alembic commands ###
