"""update show table

Revision ID: f27521e8542b
Revises: af1bd809b905
Create Date: 2024-10-22 19:54:26.414743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f27521e8542b'
down_revision = 'af1bd809b905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_genre_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
        batch_op.add_column(sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('vote_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=True))
        batch_op.drop_column('pic_url')
        batch_op.drop_column('genre_name')
        batch_op.drop_column('tmdb_genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('genre_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pic_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('release_date')
        batch_op.drop_column('vote_average')
        batch_op.drop_column('genres')
        batch_op.drop_column('tmdb_genre_ids')
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###
